name: MagesGuild
version: 1.0
main: de.heimbrodt.sten.magesguild.Main
api-version: 1.21
commands:
  mage:
    description: enables mage mode
    usage: mage
  home:
    description: teleports home
    usage: home